apiVersion: spark.apache.org/v1beta2
kind: SparkApplication
metadata:
  name: spark-job
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: docker.io/bitnami/spark:3.5.2-debian-12-r0
  imagePullPolicy: Always
  mainApplicationFile: local:////opt/spark/examples/jars/spark-examples_2.12-3.5.2.jar  # Path to the JAR file in the Docker image
  sparkVersion: 3.1.2
  restartPolicy:
    type: Never
  driver:
    cores: 1
    memory: 1g
  executor:
    cores: 1
    memory: 1g
    instances: 2
