apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-job
  namespace: airflow
spec:
  type: Scala
  mode: cluster
  image: docker.io/bitnami/spark:3.5.2-debian-12-r0
  imagePullPolicy: Always
  mainApplicationFile:/opt/bitnami/spark/examples/jars/spark-examples_2.12-3.5.2.jar  # Path to the JAR file in the Docker image
  sparkVersion: 3.5.2
  restartPolicy:
    type: Never
  labels: {}
  driver:
    cores: 1
    memory: 1g
    labels: {}
  executor:
    cores: 1
    memory: 1g
    instances: 2
    labels: {}
  mainClass: org.apache.spark.examples.SparkPi
    
