apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  namespace: airflow
spec:
  type: Scala
  mode: cluster
  image: docker.io/library/etlspeechtime:1.0.2
  imagePullPolicy: Always
  mainApplicationFile: local:///app/etlspeechtime.jar  # Path to the JAR file in the Docker image
  sparkVersion: 3.5.1
  restartPolicy:
    type: Never
  labels: {}
  driver:
    cores: 1
    memory: 1g
    labels: {}
    serviceAccount: airflow-scheduler
  executor:
    cores: 1
    memory: 1g
    instances: 2
    labels: {}
  mainClass: speech
    
