apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: simplescala
  namespace: airflow
spec:
  type: Scala
  mode: cluster
  image: "simplescala:1.0.0"
  imagePullPolicy: Always
  mainClass: "Main"
  mainApplicationFile: "local:///app/simplescala.jar"
  sparkVersion: "3.5.1"
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.5.1
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.5.1
