apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-sample
  namespace: airflow
spec:
  type: Scala
  mode: cluster
  image: verboistim/spark:3.5.1-debian-12-r7-bugfix
  imagePullPolicy: IfNotPresent
  mainApplicationFile: local:///opt/bitnami/spark/examples/jars/spark-examples_2.12-3.5.1.jar  # Path to the JAR file in the Docker image
  sparkVersion: 3.5.1
  restartPolicy:
    type: Never
  labels: {}
  driver:
    cores: 1
    memory: 1g
    labels: {}
    serviceAccount: spark-operator
  executor:
    cores: 1
    memory: 1g
    instances: 2
    labels: {}
  mainClass: org.apache.spark.examples.SparkPi
    
