apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: speech-time
  namespace: airflow
spec:
  type: Scala
  mode: cluster
  image: docker.io/library/etlspeechtime:1.0.7
  imagePullPolicy: Always
  mainApplicationFile: local:///opt/spark/examples/jars/etlspeechtime.jar
  mainClass: speech
  sparkVersion: 3.5.2
  restartPolicy:
    type: Never
  labels: {}
  driver:
    cores: 1
    memory: 1g
    labels: {}
    serviceAccount: spark-operator-spark
  executor:
    cores: 1
    memory: 1g
    instances: 2
    labels: {}
