apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: speech-time
  namespace: airflow
spec:
  type: Scala
  mode: cluster
  image: etlspeechtime:1.1.1
  imagePullPolicy: IfNotPresent
  mainApplicationFile: local:///opt/spark/examples/jars/etlspeechtime.jar
  mainClass: speech
  sparkVersion: 3.5.2
  restartPolicy:
    type: Never
  labels: {}
  driver:
    cores: 1
    memory: 2g
    labels: {}
    serviceAccount: spark-operator-spark
  executor:
    cores: 1
    memory: 2g
    instances: 2
    labels: {}
  arguments:
    - {{ params.admin }}
    - {{ params.password }}
    - http://host.docker.internal:9000
    - s3a://warehouse/micrawdata3
    - s3a://warehouse/tbl_engagement_speech_silver
    - '7776000'
