apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: speech-time
  namespace: airflow
spec:
  type: Scala
  mode: cluster
  image: etlspeechtime:2.0.0 # docker-connect-release.dr-uw2.adobeitc.com/engagement/etl-elt/etlspeechtime/etlelt:main_3
  imagePullPolicy: IfNotPresent
  mainApplicationFile: local:///opt/spark/examples/jars/etlspeechtime.jar  # Path to the JAR file in the Docker image
  mainClass: speech # Class name
  sparkVersion: 3.5.2
  restartPolicy:
    type: Never
  labels:
      version: 3.5.2
  driver:
    coreLimit: "2000m"
    cores: 2
    memory: 4g
    serviceAccount: spark-operator-spark
    labels:
      version: 3.5.2
  executor:
    cores: 2
    memory: 8g
    instances: 1
    labels:
      version: 3.5.2
  arguments: # arguments to be passed to jar main method
    - {{ params.S3_ACCESS_KEY }}
    - {{ params.S3_SECRET_KEY }}
    - {{ params.S3_END_POINT }}
    - {{ params.BRONZE_TABLE_PATH }}
    - {{ params.SILVER_TABLE_PATH }}
    - "{{ params.TIME_WINDOW_IN_SECS }}"
    - "{{ params.UPSERT_BATCH_SIZE }}"
