apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: speech-time
  namespace: airflow
spec:
  type: Scala
  mode: cluster
  image: etlspeechtime:1.0.2
  imagePullPolicy: IfNotPresent
  mainApplicationFile: local:///opt/spark/examples/jars/etlspeechtime.jar
  mainClass: speech
  sparkVersion: 3.5.2
  restartPolicy:
    type: Never
  labels: {}
  driver:
    cores: 1
    memory: 2g
    labels: {}
    serviceAccount: spark-operator-spark
    env:
      - name: BRONZE_TABLE_PATH
        value: "{{ BRONZE_TABLE_PATH }}"
      - name: SILVER_TABLE_PATH
        value: "{{ SILVER_TABLE_PATH }}"
      - name: TIME_WINDOW_IN_SECS
        value: "{{ TIME_WINDOW_IN_SECS }}"
  executor:
    cores: 1
    memory: 2g
    instances: 2
    labels: {}
    env:
      - name: BRONZE_TABLE_PATH
        value: "{{ BRONZE_TABLE_PATH }}"
      - name: SILVER_TABLE_PATH
        value: "{{ SILVER_TABLE_PATH }}"
      - name: TIME_WINDOW_IN_SECS
        value: "{{ TIME_WINDOW_IN_SECS }}"
  arguments:
    - admin
    - password
    - http://host.docker.internal:9000
    - s3a://warehouse/micrawdata1
    - s3a://warehouse/tbl_engagement_speech_silver
    - '3456000'
