apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: speech-time
  namespace: airflow
spec:
  type: Scala
  mode: cluster
  image: docker.io/apache/spark:3.5.2
  imagePullPolicy: IfNotPresent
  mainApplicationFile: local:///opt/spark/examples/jars/spark-examples_2.12-3.5.2.jar
  mainClass: org.apache.spark.examples.SparkPi
  sparkVersion: 3.5.2
  restartPolicy:
    type: Never
  labels: {}
  driver:
    cores: 1
    memory: 1g
    labels: {}
    serviceAccount: spark-operator-spark
  executor:
    cores: 1
    memory: 1g
    instances: 2
    labels: {}
